#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define LOGICAL_WIDTH 1280
#define LOGICAL_HEIGHT 720

#define WORLD_WIDTH 2000
#define WORLD_HEIGHT 2000

#define CAMERA_SPEED 800.0f
#define ZOOM_STEP 1.1f
#define MIN_ZOOM 0.2f
#define MAX_ZOOM 1.0f

#define EDGE_SCROLL_THRESHOLD 20

#define MINIMAP_SIZE 200.0f
#define MINIMAP_MARGIN 20.0f
#define MINIMAP_RANGE 60000.0f

// Density Constants
#define DENSITY_BASELINE 0.0f
#define DENSITY_PLANET_WEIGHT 0.6f
#define DENSITY_GALAXY_WEIGHT 0.8f
#define DENSITY_MAX (DENSITY_BASELINE + DENSITY_GALAXY_WEIGHT)

// Spawning
#define SPAWN_SAFE_ZONE 1500.0f
#define DESPAWN_RANGE 12000.0f
#define MAX_SIM_ANCHORS 8
#define MAX_ASTEROIDS 2048
#define MIN_DYNAMIC_ASTEROIDS 0
#define MAX_DYNAMIC_ASTEROIDS 500

// Entity Counts
#define PLANET_COUNT 8
#define GALAXY_COUNT 4
#define ASTEROID_TYPE_COUNT 16
#define DEBRIS_COUNT 8
#define MAX_PARTICLES 4096
#define MAX_UNITS 128
#define MAX_COMMANDS 16

// Game Logic
#define ASTEROID_SPEED_FACTOR 150000.0f
#define ASTEROID_ROTATION_SPEED_FACTOR 400.0f
#define ASTEROID_BASE_RADIUS_MIN 600.0f
#define ASTEROID_BASE_RADIUS_VARIANCE 3000.0f
#define ASTEROID_HEALTH_MULT 20.0f
#define ASTEROID_MIN_RADIUS 200.0f
#define ASTEROID_COLLISION_SPLIT_THRESHOLD 600.0f
#define ASTEROID_SPLIT_EXPONENT 0.5f
#define ASTEROID_SPLIT_MIN_RADIUS 300.0f

#define MOTHERSHIP_SPEED 1200.0f
#define MOTHERSHIP_FRICTION 2.0f
#define MOTHERSHIP_RADIUS 150.0f
#define MOTHERSHIP_RADAR_RANGE 8000.0f
#define ARMS_ROTATION_SPEED 0.8f
#define MAX_RADAR_BLIPS 128

// Weapons
#define LARGE_CANNON_RANGE 4000.0f
#define LARGE_CANNON_DAMAGE 25000.0f
#define LARGE_CANNON_COOLDOWN 6.0f
#define LARGE_CANNON_ENERGY_COST 100.0f
#define MAIN_CANNON_MAX_ENERGY 100.0f
#define MAIN_CANNON_REGEN_RATE 10.0f

#define SMALL_CANNON_RANGE 2000.0f
// 100 shots to destroy an average asteroid (radius 1100 * 20 health = 22000)
// 22000 / 100 = 220
#define SMALL_CANNON_DAMAGE 1500.0f
#define SMALL_CANNON_COOLDOWN 0.4f
#define SMALL_CANNON_ENERGY_COST 20.0f

// Resources
#define INITIAL_ENERGY 1000.0f
#define ENERGY_REGEN_RATE 100.0f

// UI
#define COMMAND_ICON_SIZE 60.0f
#define COMMAND_GRID_X 400.0f

#define EXPLOSION_PARTICLE_COUNT 40
#define EXPLOSION_PUFF_DIVISOR 4
#define PARTICLE_LIFE_BASE 1.0f
#define PARTICLE_LIFE_DECAY 1.5f

// Rendering
#define BG_SCALE_FACTOR 16
#define STAR_LAYER_CELL_SIZE 256
#define STAR_LAYER_PARALLAX 0.4f
#define SYSTEM_LAYER_CELL_SIZE 5000
#define SYSTEM_LAYER_PARALLAX 0.7f
#define GRID_SIZE_SMALL 200
#define GRID_SIZE_LARGE 1000
#define DENSITY_CELL_SIZE 1000
#define GRID_DENSITY_SUB_RES 2

// World Generation
#define CELESTIAL_GRID_SIZE 5000
#define CELESTIAL_GRID_SIZE_F 5000.0f

// Celestial Body Sizes
#define GALAXY_RADIUS_MIN 2000.0f
#define GALAXY_RADIUS_VARIANCE 4000.0f
#define PLANET_RADIUS_MIN 150.0f
#define PLANET_RADIUS_VARIANCE 450.0f

// Asteroid Belt Scaling
#define GALAXY_BELT_INNER_MULT 1.2f
#define GALAXY_BELT_OUTER_MULT 2.5f
#define PLANET_BELT_INNER_MULT 4.0f
#define PLANET_BELT_OUTER_MULT 10.0f

// Global Asteroid Belts (Linear)
#define GLOBAL_BELT_FREQ 0.0001f
#define GLOBAL_BELT_WIDTH 0.8f // Higher means thinner
#define GLOBAL_BELT_WEIGHT 0.5f
#define GLOBAL_BELT_ANGLE 0.6f // Radians

#define GLOBAL_BELT_SEC_FREQ 0.00015f
#define GLOBAL_BELT_SEC_WIDTH 0.6f
#define GLOBAL_BELT_SEC_WEIGHT 0.4f
#define GLOBAL_BELT_KEEP_PROB                                                  \
  0.7f // Probability (0.0-1.0) that a generated belt is actually kept

// Minimap
#define MINIMAP_LARGE_BODY_THRESHOLD 1000.0f

#endif
