#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define WORLD_WIDTH 2000
#define WORLD_HEIGHT 2000

#define CAMERA_SPEED 800.0f
#define ZOOM_STEP 1.1f
#define MIN_ZOOM 0.3f
#define MAX_ZOOM 1.0f

#define EDGE_SCROLL_THRESHOLD 20

#define MINIMAP_SIZE 200.0f
#define MINIMAP_MARGIN 20.0f
#define MINIMAP_RANGE 60000.0f

// Density Constants
#define DENSITY_BASELINE 0.2f
#define DENSITY_PLANET_WEIGHT 0.6f
#define DENSITY_GALAXY_WEIGHT 0.8f
#define DENSITY_MAX (DENSITY_BASELINE + DENSITY_GALAXY_WEIGHT)

// Spawning
#define SPAWN_SAFE_ZONE 1500.0f
#define DESPAWN_RANGE 12000.0f
#define MAX_ASTEROIDS 2048
#define MIN_DYNAMIC_ASTEROIDS 20
#define MAX_DYNAMIC_ASTEROIDS 100

// Entity Counts
#define PLANET_COUNT 8
#define GALAXY_COUNT 4
#define ASTEROID_TYPE_COUNT 16
#define MAX_PARTICLES 4096

// Game Logic
#define ASTEROID_SPEED_FACTOR 15000.0f
#define ASTEROID_ROTATION_SPEED_FACTOR 400.0f
#define ASTEROID_BASE_RADIUS_MIN 80.0f
#define ASTEROID_BASE_RADIUS_VARIANCE 120
#define ASTEROID_COLLISION_SPLIT_THRESHOLD 60.0f
#define ASTEROID_SPLIT_FACTOR 0.6f

#define EXPLOSION_PARTICLE_COUNT 40
#define EXPLOSION_PUFF_DIVISOR 4
#define PARTICLE_LIFE_BASE 1.0f
#define PARTICLE_LIFE_DECAY 1.5f

// Rendering
#define BG_SCALE_FACTOR 16
#define STAR_LAYER_CELL_SIZE 256
#define STAR_LAYER_PARALLAX 0.4f
#define SYSTEM_LAYER_CELL_SIZE 5000
#define SYSTEM_LAYER_PARALLAX 0.7f
#define GRID_SIZE_SMALL 200
#define GRID_SIZE_LARGE 1000
#define DENSITY_CELL_SIZE 1000
#define GRID_DENSITY_SUB_RES 2

// World Generation
#define CELESTIAL_GRID_SIZE 5000
#define CELESTIAL_GRID_SIZE_F 5000.0f

// Celestial Body Sizes
#define GALAXY_RADIUS_MIN 2000.0f
#define GALAXY_RADIUS_VARIANCE 4000.0f
#define PLANET_RADIUS_MIN 150.0f
#define PLANET_RADIUS_VARIANCE 450.0f

// Asteroid Belt Scaling
#define GALAXY_BELT_INNER_MULT 1.2f
#define GALAXY_BELT_OUTER_MULT 2.5f
#define PLANET_BELT_INNER_MULT 4.0f
#define PLANET_BELT_OUTER_MULT 10.0f

// Global Asteroid Belts (Linear)
#define GLOBAL_BELT_FREQ 0.0001f
#define GLOBAL_BELT_WIDTH                                                      \
  0.8f // Higher means thinner belts (threshold for sine)
#define GLOBAL_BELT_WEIGHT 0.5f
#define GLOBAL_BELT_ANGLE 0.6f // Radians

#define GLOBAL_BELT_SEC_FREQ 0.00015f
#define GLOBAL_BELT_SEC_WIDTH 0.6f
#define GLOBAL_BELT_SEC_WEIGHT 0.4f
#define GLOBAL_BELT_KEEP_PROB                                                  \
  0.7f // Probability (0.0-1.0) that a generated belt is actually kept

// Minimap
#define MINIMAP_LARGE_BODY_THRESHOLD 1000.0f

#endif
