#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define LOGICAL_WIDTH 1280
#define LOGICAL_HEIGHT 720

#define WORLD_WIDTH 2000
#define WORLD_HEIGHT 2000

#define CAMERA_SPEED 800.0f
#define ZOOM_STEP 1.1f
#define MIN_ZOOM 0.2f
#define MAX_ZOOM 1.0f

#define EDGE_SCROLL_THRESHOLD 20

#define MINIMAP_SIZE 200.0f
#define MINIMAP_MARGIN 20.0f
#define MINIMAP_RANGE 60000.0f

// Density Constants
#define DENSITY_BASELINE 0.0f
#define DENSITY_PLANET_WEIGHT 0.6f
#define DENSITY_GALAXY_WEIGHT 0.8f
#define DENSITY_MAX (DENSITY_BASELINE + DENSITY_GALAXY_WEIGHT)

// Spawning
#define SPAWN_SAFE_ZONE 1500.0f
#define SPAWN_MIN_DIST 4500.0f
#define SPAWN_BUFFER 1000.0f
#define ASTEROID_SPAWN_ATTEMPTS 15
#define CRYSTAL_SPAWN_ATTEMPTS 10
#define RESPAWN_ATTEMPTS 10
#define RESPAWN_RANGE 5000.0f
#define RESPAWN_BUFFER 500.0f
#define DESPAWN_RANGE 12000.0f
#define MAX_SIM_ANCHORS 8
#define MAX_ASTEROIDS 2048
#define MIN_DYNAMIC_ASTEROIDS 0
#define MAX_DYNAMIC_ASTEROIDS 500

// Entity Counts
#define PLANET_COUNT 8
#define GALAXY_COUNT 4
#define ASTEROID_TYPE_COUNT 16
#define CRYSTAL_COUNT 8
#define DEBRIS_COUNT 8
#define MAX_PARTICLES 4096
#define MAX_UNITS 128
#define MAX_COMMANDS 16

// Crystal Resources
#define CRYSTAL_PROB_PLANET 0.001f
#define CRYSTAL_PROB_GALAXY 0.005f
#define CRYSTAL_RADIUS_SMALL_MIN 40.0f
#define CRYSTAL_RADIUS_SMALL_VARIANCE 40.0f
#define CRYSTAL_RADIUS_LARGE_MIN 400.0f
#define CRYSTAL_RADIUS_LARGE_VARIANCE 600.0f
#define CRYSTAL_VALUE_MULT 5.0f // Resource per unit of radius
#define CRYSTAL_VISUAL_SCALE 3.0f
#define MAX_RESOURCES 128

// Game Logic
#define ASTEROID_SPEED_FACTOR 300000.0f
#define ASTEROID_ROTATION_SPEED_FACTOR 400.0f
#define ASTEROID_BASE_RADIUS_MIN 600.0f
#define ASTEROID_BASE_RADIUS_VARIANCE 3000.0f
#define ASTEROID_HEALTH_MULT 20.0f
#define ASTEROID_MIN_RADIUS 200.0f
#define ASTEROID_COLLISION_SPLIT_THRESHOLD 600.0f
#define ASTEROID_SPLIT_EXPONENT 0.5f
#define ASTEROID_SPLIT_MIN_RADIUS 300.0f
#define ASTEROID_HITBOX_MULT 0.35f
#define ASTEROID_VISUAL_SCALE 1.0f
#define ASTEROID_CORE_SCALE 0.35f

#define PLANET_VISUAL_SCALE 1.1f
#define GALAXY_VISUAL_SCALE 1.0f
#define MOTHERSHIP_VISUAL_SCALE 2.6f
#define GRAVITY_MAX_FORCE 50000000.0f
#define GRAVITY_MIN_FORCE 10000000.0f
#define GRAVITY_MIN_DIST 100.0f

#define MOTHERSHIP_SPEED 1200.0f
#define MOTHERSHIP_FRICTION 2.0f
#define MOTHERSHIP_RADIUS 150.0f
#define MOTHERSHIP_RADAR_RANGE 8000.0f
#define ARMS_ROTATION_SPEED 0.8f
#define MAX_RADAR_BLIPS 128

// Mothership Visuals
#define MOTHERSHIP_CORE_COUNT 5
#define MOTHERSHIP_WORLD_SCALE_DIVISOR 8.0f

#define UNIT_STOP_DIST 50.0f
#define UNIT_BRAKING_DIST 800.0f
#define UNIT_STEERING_FORCE 4.0f
#define UNIT_ROTATION_SPEED 0.1f
#define RESPAWN_TIME 3.0f

// Production
#define MAX_PRODUCTION_QUEUE 5
#define MINER_COST 100.0f
#define MINER_BUILD_TIME 5.0f
#define FIGHTER_COST 150.0f
#define FIGHTER_BUILD_TIME 8.0f

// Weapons
#define WEAPON_FIRING_RANGE_MULT 0.66f
#define LASER_START_OFFSET_MULT 10.5f
#define LASER_THICKNESS_MULT 0.2f
#define LASER_GLOW_MULT 2.0f
#define LASER_CORE_THICKNESS_MULT 0.3f

#define WARNING_RANGE_FAR 8000.0f
#define WARNING_RANGE_MID 4000.0f
#define WARNING_RANGE_NEAR 2000.0f

#define LARGE_CANNON_RANGE 5000.0f
#define LARGE_CANNON_DAMAGE 25000.0f
#define LARGE_CANNON_COOLDOWN 10.0f
#define LARGE_CANNON_ENERGY_COST 100.0f
#define MAIN_CANNON_MAX_ENERGY 100.0f
#define MAIN_CANNON_REGEN_RATE 10.0f

#define SMALL_CANNON_RANGE 3000.0f
#define SMALL_CANNON_DAMAGE 1500.0f
#define SMALL_CANNON_COOLDOWN 0.3f
#define SMALL_CANNON_ENERGY_COST 20.0f

// Particles
#define MUZZLE_FLASH_LIFE 0.6f
#define MUZZLE_FLASH_SIZE_MULT 4.0f
#define PARTICLE_LIFE_BASE 1.0f
#define PARTICLE_LIFE_DECAY 1.5f

// Colors (RGBA)
#define COLOR_LASER_RED (SDL_Color){255, 50, 50, 255}
#define COLOR_MUZZLE_FLASH (SDL_Color){255, 100, 100, 255}
#define COLOR_HUD_HEALTH (SDL_Color){100, 255, 100, 255}
#define COLOR_HUD_ENERGY (SDL_Color){50, 150, 255, 255}
#define COLOR_HUD_MAIN_CANNON (SDL_Color){200, 50, 255, 255}

// Resources
#define INITIAL_ENERGY 1000.0f
#define ENERGY_REGEN_RATE 100.0f

// UI Icons
#define ICON_MOVE 0
#define ICON_ATTACK 1
#define ICON_PATROL 2
#define ICON_STOP 3
#define ICON_OFFENSIVE 4
#define ICON_DEFENSIVE 5
#define ICON_HOLD 6
#define ICON_MAIN_CANNON 7
#define ICON_BACK 8
#define ICON_GATHER 9
#define ICON_RETURN 10
#define ICON_COUNT 11

#define CMD_ICON_SIZE 60.0f

#define MAX_LOGS 8

#define EXPLOSION_PARTICLE_COUNT 40
#define EXPLOSION_PUFF_DIVISOR 4

// Rendering
#define MOTHERSHIP_FX_TEXTURE_SIZE 128
#define BG_SCALE_FACTOR 16
#define STAR_LAYER_CELL_SIZE 256
#define STAR_LAYER_PARALLAX 0.4f
#define SYSTEM_LAYER_CELL_SIZE 5000
#define SYSTEM_LAYER_PARALLAX 0.7f
#define GRID_SIZE_SMALL 200
#define GRID_SIZE_LARGE 1000
#define DENSITY_CELL_SIZE 2000
#define GRID_DENSITY_SUB_RES 1

// World Generation
#define CELESTIAL_GRID_SIZE 5000
#define CELESTIAL_GRID_SIZE_F 5000.0f

// Celestial Body Sizes
#define GALAXY_RADIUS_MIN 6000.0f
#define GALAXY_RADIUS_VARIANCE 12000.0f
#define PLANET_RADIUS_MIN 400.0f
#define PLANET_RADIUS_VARIANCE 1200.0f

// Asteroid Belt Scaling
#define GALAXY_BELT_INNER_MULT 0.4f
#define GALAXY_BELT_OUTER_MULT 4.0f
#define PLANET_BELT_INNER_MULT 3.0f
#define PLANET_BELT_OUTER_MULT 12.0f

// Global Asteroid Belts (Linear)
#define GLOBAL_BELT_FREQ 0.0001f
#define GLOBAL_BELT_WIDTH 0.8f
#define GLOBAL_BELT_WEIGHT 0.5f
#define GLOBAL_BELT_ANGLE 0.6f

#define GLOBAL_BELT_SEC_FREQ 0.00015f
#define GLOBAL_BELT_SEC_WIDTH 0.6f
#define GLOBAL_BELT_SEC_WEIGHT 0.4f
#define GLOBAL_BELT_KEEP_PROB 0.7f

// Minimap
#define MINIMAP_LARGE_BODY_THRESHOLD 1000.0f

#endif